name: Commits
on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  
jobs:
  count_commits:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Obtenir Commits dels usuaris
        id: get_contributors
        run: |
          python metrics.py
      - name: Committing results
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          git add metrics.json
          git commit -m "Actualitzar metrics.json" || exit 0
          git push
